---
kind: pipeline
name: nodejs

steps:
  - name: test
    image: node:12-alpine
    commands:
      - cd js
      - npm ci
      - npm test

---
kind: pipeline
name: reasonml

steps:
  - name: test
    image: node:12
    commands:
      - cd re
      - yarn install
      - yarn build
      - yarn test

---
kind: pipeline
name: clojure

steps:
  - name: test
    image: clojure
    commands:
      - cd clj
      - lein test

---
kind: pipeline
name: v

steps:
  - name: test
    image: kcjpop/vlang
    commands:
      - cd v
      - v --version
      - v -g test main
